// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using shipping.DBContext;

#nullable disable

namespace shipping.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20250512145124_updatebt")]
    partial class updatebt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("shipping.Model.BienTheSanPham", b =>
                {
                    b.Property<string>("IDBienTheSanPham")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Gia")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<byte[]>("HinhAnh")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("IDSanPham")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SKU")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("IDBienTheSanPham");

                    b.HasIndex("IDSanPham");

                    b.ToTable("BienTheSanPham");
                });

            modelBuilder.Entity("shipping.Model.ChiTietBienTheSanPham", b =>
                {
                    b.Property<int>("IDChiTietBTSanPham")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDChiTietBTSanPham"));

                    b.Property<string>("IDBienTheSanPham")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("IDGiaTriBienTheSanPham")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDChiTietBTSanPham");

                    b.HasIndex("IDBienTheSanPham");

                    b.HasIndex("IDGiaTriBienTheSanPham");

                    b.ToTable("ChiTietBienTheSanPham");
                });

            modelBuilder.Entity("shipping.Model.ChiTietDVVanChuyen", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IDCuaHang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IDDonViVanChuyen")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<int>("PhiVanChuyen")
                        .HasColumnType("int");

                    b.Property<string>("ThoiGianDuKien")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("IDDonViVanChuyen");

                    b.ToTable("ChiTietDVVanChuyen");
                });

            modelBuilder.Entity("shipping.Model.DanhMuc", b =>
                {
                    b.Property<int>("IDDanhMuc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDDanhMuc"));

                    b.Property<int>("CapDanhMuc")
                        .HasColumnType("int");

                    b.Property<bool>("IsLeaf")
                        .HasColumnType("bit");

                    b.Property<string>("Path")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDanhMuc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThai")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDDanhMuc");

                    b.ToTable("DanhMuc");
                });

            modelBuilder.Entity("shipping.Model.DonViVanChuyen", b =>
                {
                    b.Property<string>("IDDonViVanChuyen")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoDienThoai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDonVi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDDonViVanChuyen");

                    b.ToTable("DonViVanChuyen");
                });

            modelBuilder.Entity("shipping.Model.GiaTriBTSP", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("IDThuocTinh")
                        .HasColumnType("int");

                    b.Property<string>("TenGiaTri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("IDThuocTinh");

                    b.ToTable("GiaTriBTSP");
                });

            modelBuilder.Entity("shipping.Model.Images", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("HinhAnh")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("IDSanPham")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SanPhamIDSanPham")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("SanPhamIDSanPham");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("shipping.Model.SanPham", b =>
                {
                    b.Property<string>("IDSanPham")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("IDCuaHang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IDDanhMuc")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenSanPham")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThai")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDSanPham");

                    b.HasIndex("IDDanhMuc");

                    b.ToTable("SanPham");
                });

            modelBuilder.Entity("shipping.Model.ThuocTinhBTSP", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("TenThuocTinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("ThuocTinhBTSP");
                });

            modelBuilder.Entity("shipping.Model.BienTheSanPham", b =>
                {
                    b.HasOne("shipping.Model.SanPham", "SanPham")
                        .WithMany("BienThes")
                        .HasForeignKey("IDSanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("shipping.Model.ChiTietBienTheSanPham", b =>
                {
                    b.HasOne("shipping.Model.BienTheSanPham", "BienTheSanPham")
                        .WithMany("ChiTietBienThes")
                        .HasForeignKey("IDBienTheSanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("shipping.Model.GiaTriBTSP", "GiaTri")
                        .WithMany("ChiTietBienThes")
                        .HasForeignKey("IDGiaTriBienTheSanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BienTheSanPham");

                    b.Navigation("GiaTri");
                });

            modelBuilder.Entity("shipping.Model.ChiTietDVVanChuyen", b =>
                {
                    b.HasOne("shipping.Model.DonViVanChuyen", "DonViVanChuyen")
                        .WithMany("ChiTietDVVanChuyens")
                        .HasForeignKey("IDDonViVanChuyen")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DonViVanChuyen");
                });

            modelBuilder.Entity("shipping.Model.GiaTriBTSP", b =>
                {
                    b.HasOne("shipping.Model.ThuocTinhBTSP", "ThuocTinh")
                        .WithMany("GiaTris")
                        .HasForeignKey("IDThuocTinh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ThuocTinh");
                });

            modelBuilder.Entity("shipping.Model.Images", b =>
                {
                    b.HasOne("shipping.Model.SanPham", null)
                        .WithMany("Images")
                        .HasForeignKey("SanPhamIDSanPham");
                });

            modelBuilder.Entity("shipping.Model.SanPham", b =>
                {
                    b.HasOne("shipping.Model.DanhMuc", "DanhMuc")
                        .WithMany("SanPhams")
                        .HasForeignKey("IDDanhMuc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DanhMuc");
                });

            modelBuilder.Entity("shipping.Model.BienTheSanPham", b =>
                {
                    b.Navigation("ChiTietBienThes");
                });

            modelBuilder.Entity("shipping.Model.DanhMuc", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("shipping.Model.DonViVanChuyen", b =>
                {
                    b.Navigation("ChiTietDVVanChuyens");
                });

            modelBuilder.Entity("shipping.Model.GiaTriBTSP", b =>
                {
                    b.Navigation("ChiTietBienThes");
                });

            modelBuilder.Entity("shipping.Model.SanPham", b =>
                {
                    b.Navigation("BienThes");

                    b.Navigation("Images");
                });

            modelBuilder.Entity("shipping.Model.ThuocTinhBTSP", b =>
                {
                    b.Navigation("GiaTris");
                });
#pragma warning restore 612, 618
        }
    }
}
